[package]
name = "cards"
version = "0.1.0"
entrypoint = "mod.typ"
authors = ["Yves Par√®s"]
license = "MIT"
description = "Render card-like containers"
repository = "https://github.com/YPares/typstware"
